### ISSUE TITLE
ImageOverlay `loading_state` prop not updating

### ISSUE THREAD

**Issue by prl900** [emilhe/dash-leaflet#196]
In the previous version of dash-leaflet, the `loaded` prop was added to ImageOverlay to notify when a resource had finished loading -- see #182 

In this new version, there is a `loading_state` prop that seems to do a similar thing. However, this prop doesn't seem to update on ImageOverlay loading events.

Here is a simple code to reproduce the problem:
```
import dash_leaflet as dl
from dash import Dash, html, callback, Input, Output

image_bounds = [[40.712216, -74.22655], [40.773941, -74.12544]]
app = Dash()
app.layout = html.Div([
    dl.Map([
            dl.ImageOverlay(
                id="im-overlay",
                opacity=0.5, 
                url="https://upload.wikimedia.org/wikipedia/commons/9/95/Arctostaphylos-uva-ursi.JPG", 
                bounds=image_bounds), 
            dl.TileLayer()
        ], 
        bounds=image_bounds, 
        style={'height': '50vh'}
    ),
    html.Div(id="out-text")
])


@callback(
    Output("out-text", "children"),
    Input("im-overlay", "loading_state"),
)
def update_loaded(loading):
    print("loading state", loading)

    return "loaded!"

if __name__ == '__main__':
    app.run_server()
```

In this case, the callback doesn't fire when the image has been downloaded and the prop seems to be always `None`.

Not sure if I'm using the new props correctly but any help with handling load events in dash-leaflet would be greatly appreciated.

**Comment by emilhe** [comment]
The `loading_state` property is a Dash-thing, not related to `dash-leaflet` itself. I believe that you are looking for the `n_loads` property. The change in name as compared to before was to doone streamline [event property naming across the board](https://www.dash-leaflet.com/docs/events).

**Comment by prl900** [comment]
Thanks @emilhe, the `n_loads` property does the trick. I like this solution btw, a simple loading counter, nice!
